const DIFFICULTY=4;
const MINE_RATE=3000;//3 sec
const INITIAL_BALENCE=3000;
const MINING_REWARD=10
const LIQUIDITY_POOL_BALENCE=100000
module.exports={DIFFICULTY,MINE_RATE,INITIAL_BALENCE,MINING_REWARD,LIQUIDITY_POOL_BALENCE};